service: numbers
#app: numerouno
#tenant: clybs

plugins:
  - serverless-plugin-dynamodb-autoscaling

custom:
  tableName: 'numbers-table-${self:provider.stage}'
  dynamodbAutoscaling:
    tablesConfig:
      # Tweak minCapacity setting for tableName (for both table and indexes)
      tableName:
        minCapacity: 2

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: ap-southeast-1
  iamRoleStatements:
  - Effect: Allow
    Action:
    - dynamodb:Query
    - dynamodb:Scan
    - dynamodb:GetItem
    - dynamodb:PutItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
    Resource:
    - { "Fn::GetAtt": ["NumbersDynamoDBTable", "Arn" ] }
    - Fn::Join:
      - "/"
      -
        - { "Fn::GetAtt": ["NumbersDynamoDBTable", "Arn" ] }
        - "index/*"
  environment:
    NUMBERS_TABLE: ${self:custom.tableName}

functions:
  postNumber:
    handler: index.handler
    events:
    - http: 'POST /numbers'
    - http: 'POST /numbers/terminate/{proxy+}'
  getNumber:
    handler: index.handler
    events:
    - http: 'GET /numbers'
    - http: 'GET /numbers/{proxy+}'
  putNumber:
    handler: index.handler
    events:
    - http: 'PUT /numbers/{proxy+}'
  deleteNumber:
    handler: index.handler
    events:
    - http: 'DELETE /numbers/{proxy+}'

resources:
  Resources:
    NumbersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
        - AttributeName: number
          AttributeType: S
        - AttributeName: block
          AttributeType: S
        - AttributeName: available
          AttributeType: S
        KeySchema:
        - AttributeName: number
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${self:custom.tableName}
        GlobalSecondaryIndexes:
        - IndexName: BlockIndex
          KeySchema:
          - AttributeName: block
            KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        - IndexName: AvailableIndex
          KeySchema:
          - AttributeName: available
            KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5


